Ben84FFM/BurgerGuide

- client/src/App.jsx
- client/src/Components/Hero.jsx
- client/src/Components/LoginForm.jsx
- client/src/Components/Navbar.jsx
- client/src/Components/Post.jsx
- client/src/Components/RegisterForm.jsx
- client/src/Components/Search.jsx
Adaptation Containers for Login Registration
Bugfixing
> AdaptationLogin

- client/src/Components/BurgerRating.jsx
- server/index.js
initial Implementation RatingfFunction for client
> RatingFunction

- client/src/Components/BurgerRating.jsx
> AdaptationBurgerRating

- client/src/App.jsx
- client/src/Components/BurgerRating.jsx
- client/src/Components/addRestaurant.jsx
add Function addRestaurant - simple interface. 
fetchFunction, axios. - clientside
> addRestaurantFunktionClient

- client/src/App.jsx
- client/src/Components/BurgerRating.jsx
> DebuggingModelPostRestaurant

- client/src/Components/Navbar.jsx
> NavigationBurgerStores

- server/controllers/restaurant.js
- server/routes/postRestaurant.js
> BurgerStore

- client/src/App.jsx
- client/src/Components/Restaurant.jsx
- client/src/Components/Search.jsx
> LinkToItem

- client/src/Components/Search.jsx
implement first searchDesign for RestaurantOutPut
> SerachDesignAdapataion1

- client/src/Components/Hero.jsx
- client/src/Components/SearchRestaurant.jsx
- server/models/Restaurant2.js
Design Adaptation Frontend SearchFunction&Button
> DesignAdaptationSearchfunction

- client/src/Components/AboutUs.jsx
- client/src/Components/Footer.jsx
- client/src/Components/Navbar.jsx
modifiedDesign:   src/Components/AboutUs/NavBar/Footer/
> modiefiedNavbarFooterAboutUs

- client/src/Components/RegisterForm.jsx
modified design Components RegisterForm
> modifiedRegisterForm

- client/src/Components/AboutUs.jsx
- client/src/Components/Hero.jsx
- client/src/Components/LoginForm.jsx
- client/src/Components/RegisterForm.jsx
- client/src/Components/Search.jsx
modifieded Design: AboutUs, Hero, LoginForm, RegisterForm.jsx, Search.jsx,
> Designmodifications

- client/src/Components/Search.jsx
Bugfixing Scroll and RestaurantLoad
> BugfixingSearchFunctionScroll

- client/src/App.jsx
- client/src/Components/new.jsx
Design for add a new Restaurant
> DesignnewRestaurant

- client/src/Components/Search.jsx
- client/src/Components/addRestaurant.jsx
> bugfixingRestaurantContainer

- client/src/Components/SearchTest.jsx
> bugfxingSearchBar

- client/src/Components/SearchTest.jsx
adaptatoion SearchBar - loadingItems directly by input
> searchbarDirektloadingofArray

- client/src/Components/SearchTest.jsx
ChangesSearchFunktionDesign&Function
> ChangesSearchFunktionDesign&Function

- client/src/Components/SearchTest.jsx
Search Function adaptation loading Items - empty searchfield no results
> SearchFunctionadaptationBugfixing

- client/src/Components/SearchTest.jsx
implement LinkButton in SearchFunction to navigate to add new BurgerStore
> navigationaddRestaurantimplementation

- client/src/Components/AboutUs.jsx
- client/src/Components/Navbar.jsx
- client/src/Components/SearchTest.jsx
Adaptation NavbarResponsive for login&Logout
> DesignResponsiveNavbar

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/Components/Hero.jsx
- client/src/Components/SearchTest.jsx
- client/src/Components/StoreCarousel.jsx
- client/src/Components/StoreDetail.jsx
- client/src/Components/addRestaurant.jsx
ImplementCarouselFunction
Implement in HeroSection
DataFetched and Renderin in Frontend
Currently no bugs
> ImplementCarouselFunction

- client/src/App.jsx
- client/src/Components/StoreCarousel.jsx
- client/src/Components/StoreDetail.jsx
add a simple design for singleBurgerStores with structur for comments and reviews.
> DesignStoreDetailsforComments&reviews

- client/src/Components/StoreCarousel.jsx
- client/src/Components/StoreDetail.jsx
implement navigation from carousel items to singlePageStore
> LinkNavigation

- client/src/App.jsx
- client/src/Components/Hero.jsx
- client/src/Components/Navbar.jsx
- client/src/Components/StoreCarousel.jsx
- client/src/Components/StoreDetail.jsx
- client/src/Components/StoreRating.jsx
Bugfixing for fetchData - implememt a Design for SingleStores
Bugfix Containers - HeroSection (implement Rout Button) Bugfix Container FrontendCarousell
> BugfixingFrontendDesignFrontend

- client/src/Components/SearchTest.jsx
- client/src/Components/StoreCarouselSearch.jsx
- client/src/Components/addStore.jsx
Adaptation Searchfunction 
Implement 2nd Carousel at SearchTest / Frontend Design
> SearchChanges

- client/.eslintrc.cjs
> adapeslintcjs

- client/src/App.jsx
- client/src/Components/StoreDetail.jsx
- client/src/Components/StoreRating.jsx
- server/controllers/review.js
- server/routes/reviewRouter.js
Implement ReviewFunction including routes, router
> Implement ReviewFunction with routes

- client/src/App.jsx
- client/src/Components/StoreDetail.jsx
- client/src/Components/StoreRating.jsx
- client/src/Components/addStore.jsx
bugfix addStore- now its functional.
> bugfixaddStore

- client/package-lock.json
- client/package.json
- client/src/Components/StoreDetail.jsx
> MapFuntion

- client/src/App.jsx
- client/src/Components/AboutUs.jsx
- client/src/Components/ContactUs.jsx
- client/src/Components/Footer.jsx
- client/src/Components/SearchTest.jsx
- client/src/Components/StoreCarouselSearch.jsx
- client/src/Components/TechStackCarousel.jsx
- client/src/Components/dataPolicy.jsx
- server/routes/storeRouter.js
Implement:
Design for AboutUs / Search/
Implement DataPolicyRoute/Site/Design
Implement TechStack Design Frontend / Aboutus
> DesignFrontendAboutus&Stores

- client/src/Components/BackgroundCarousel.jsx
- client/src/Components/Footer.jsx
- client/src/Components/SearchTest.jsx
- client/src/Components/addStore.jsx
Bigfix Button SearchFunktion/ add Restaurant /
> bufgfixingSearchBUtton

- client/src/App.css
- client/src/Components/AboutUs.jsx
- client/src/Components/BackgroundCarousel.jsx
- client/src/Components/Footer.jsx
- client/src/Components/StackCarousel.jsx
- server/controllers/review.js
DesignAbout us implement Borders and Design changes
> bugfixbackendSearch&DesignAbout us

- client/src/Components/AboutUs.jsx
DesignChangesAboutUs Bugfix Carousel
> DesignChangesAboutUS

- client/src/Components/AboutUs.jsx
- client/src/Components/DynamicBackground.jsx
- client/src/Components/Hero.jsx
- client/src/Components/SearchTest.jsx
- client/src/Components/dataPolicy.jsx
implement the same DynamicBackground for Home, DataPoilcy: 
Designchange DataPolicySite.
> implementDynamicBackground

- client/src/Components/DynamicBackground.jsx
BugfixDynamicBackground - transition
> BugfixDynamicBackground

- client/src/Components/Navbar.jsx
- client/src/Components/StoreDetail.jsx
> bugfixNavbarStoreDetails

- client/src/Components/AboutUs.jsx
- client/src/Components/AboutusMockup.jsx
- client/src/Components/DynamicBackground.jsx
- client/src/Components/Footer.jsx
- client/src/Components/Hero.jsx
- client/src/Components/Impress.jsx
- client/src/Components/StoreDetail.jsx
- client/src/Components/StoreRating.jsx
- client/src/Components/dataPolicy.jsx
DesignChangesBugfix
Footer, About Us, StoreRating, StoreDetail, Imprint, DataPolicy.
Bugfix Mappfunction to be responsive
> DesignChangesBugfix

- client/src/Components/Hero.jsx
- client/src/Components/Impress.jsx
- client/src/Components/StoreDetail.jsx
- client/src/Components/StoreRating.jsx
- client/src/Components/dataPolicy.jsx
> bugfixHome&Rating

- client/src/Components/Hero.jsx
> bugfixHome

- client/src/Components/LoginForm.jsx
- client/src/Components/RegisterForm.jsx
- client/src/Components/Search.jsx
- client/src/Components/StoreCarouselSearch.jsx
- client/src/Components/addStore.jsx
bugfixDesignConfig LoginFeld/ Registration/AddStore ect,
> bugfixDesignConfig

- client/src/Components/AboutUs.jsx
- client/src/Components/StoreRating.jsx
BugFixRateFunktion implement that after the rating, the ratingcomponet is closing
> BugFixRateFunktion
